gxm: Optimize graphics hashing with XXH3
Vita3K/Vita3K pull request #1016
Opened 2020-11-12 17:20 UTC by EXtremeExploit

* XXH3 is faster than accumulate and SHA256
* Also optimize nids find inside resolve_export function
# Testing
Since my PC is not that great i am unable to detect any performance boost with this, but technically it should, if someone could do some benchmarking justo to get some numbers would be great

2020-11-14 17:14 UTC, sunho requested changes
This is clever optimization but this hash value is used to identify the shader from various games. Using different hashing algorithm will break the database of shaders collected for debugging purpose (e.g. shader 342hlsfd3424 from game A is broken)

2020-11-14 17:19 UTC, sunho commented
I thought about having an option to enable this optimization but that would confuse communication sometimes. (e.g. tester gives a shader log to developer but the names are different) So, I'm afraid we shouldn't pull this change if the issues I mentioned are not addressed.

2020-11-14 17:23 UTC, Frain-Breeze commented
You could add a prefix to the hash to identify what algorithm was used, like xxh3_HASH.

2020-11-14 19:06 UTC, sunho commented
We can take change in texture_cache.cpp confidently, can you separate the pr?

2020-11-14 19:55 UTC, EXtremeExploit commented
Should i also remove the changes to [this file](https://github.com/Vita3K/Vita3K/pull/1016/files#diff-5ff5ee152e1a16923b44fa35ba31fc48b696354b521ccadd88e3fdc233113ee7R58) ?

2020-11-15 05:36 UTC, sunho commented
That looks great. 👍 Just the part that change the name of shader is problematic.

2020-11-15 20:39 UTC, sunho approved these changes
:)

2020-11-15 20:40 UTC, sunho commented
I'm sorry for rejecting some of your code.

2020-11-15 20:40 UTC, merged

2020-11-15 20:42 UTC, sunho commented
I just noticed that xxHash is not added in cmake file. Is it okay?

2020-11-15 21:45 UTC, EXtremeExploit commented
it worked just fine and the compilation didn't fail so i guess its ok