gui: improve font format support.
Vita3K/Vita3K pull request #1112
Opened 2021-01-25 16:44 UTC by Zangetsu38

split more lang pr for get good support on all font can exist now

2021-01-26 18:26 UTC, frangarcj requested changes

2021-01-26 18:26 UTC, frangarcj commented on vita3k/gui/src/gui.cpp
> +        LOG_WARN("Could not find firmware font file at \"{}\", install firmware fonts package for fix this.", latin_fw_font_path.string());
to fix this

2021-01-27 02:52 UTC, 1whatleytay approved these changes

2021-01-27 13:21 UTC, frangarcj approved these changes

2021-01-27 13:23 UTC, merged