gxm: Improve cube textures
Vita3K/Vita3K pull request #1214
Opened 2021-04-04 14:51 UTC by scribam

Testing required

2021-04-04 19:47 UTC, Zangetsu38 commented on vita3k/modules/SceGxm/SceGxm.cpp
> +    const int result = init_texture_base(export_name, texture, data, texFormat, width, height, mipCount, SCE_GXM_TEXTURE_CUBE_ARBITRARY);
Is same init cube, is keep stub, cube request also works for shader

2021-04-06 16:45 UTC, pent0 reviewed
Cube can't be uploaded the same as normal texture for now (it's store a bit different in memory), but if does not crash and increase compatibility, it's ok

2021-04-06 20:01 UTC, Zangetsu38 requested changes
Only need add this, is like initcube, request works on shader

2021-04-06 20:01 UTC, Zangetsu38 commented on vita3k/modules/SceGxm/SceGxm.cpp
> +
```suggestion
    STUBBED("Stub InitCubeArbitrary");
```

2021-04-08 06:03 UTC, Zangetsu38 approved these changes

2021-04-08 06:03 UTC, merged