audio: Programmatic audio control
Vita3K/Vita3K pull request #1215
Opened 2021-04-05 14:26 UTC by tictakk

Implementing sceAudioOutSetVolume to allow software to adjust volume

This turns out to be a little more complicated than expected. Since audio relies on the **SDL_MixAudio** function, that function takes a volume param and applies the volume when mixing the samples. But the sceAudioOutSetVolume function can specify which channel it wants to lower volume on, which you cannot do with SDL_MixAudio. What I did in this PR is average the left and right channel volumes together and applied that to the **SDL_MixAudio** function, which I'm assuming we're not going to want to do. 

Possible solutions:
Apply the volume to the samples in the streams before mixing, but then we're running essentially the same function twice over the same set of sample data, also we'd have to account for every possible format the sample data can be received in.

Mix our own audio, which wouldn't be too hard, just mimicking what SDL_MixAudio does, but accounting for individual channels. 

I may be making this way more complicated than it is an there's an obvious solution that I am missing or don't know about.

2021-04-05 15:57 UTC, pent0 requested changes

2021-04-05 15:57 UTC, pent0 commented on vita3k/audio/include/audio/state.h
> +    float volume = 100.0;
If this is intended to br from 0.0f to 1.0f make it 1.0f by default

2021-04-05 15:57 UTC, pent0 commented on vita3k/audio/src/audio.cpp
> +    const int vol = SDL_MIX_MAXVOLUME * port.volume;
```suggestion
    const int vol = static_cast<int>(SDL_MIX_MAXVOLUME * port.volume);
```

2021-04-05 15:57 UTC, pent0 commented on vita3k/audio/src/audio.cpp
> +    const int vol = SDL_MIX_MAXVOLUME * port.volume;
Warning if no cast

2021-04-05 15:57 UTC, pent0 commented on vita3k/modules/SceAudio/SceAudio.cpp
> +    int left = *vol;
Also check channelFlags, there might be instances where only one channel is to be set

2021-04-05 15:57 UTC, pent0 commented on vita3k/modules/SceAudio/SceAudio.cpp
> +    int left = *vol;
```suggestion
    const int left = vol[0];
```

2021-04-05 15:57 UTC, pent0 commented on vita3k/modules/SceAudio/SceAudio.cpp
> +    int right = *vol++;
Same

2021-04-05 15:57 UTC, pent0 commented on vita3k/modules/SceAudio/SceAudio.cpp
> +    float volume = ((float)((left + right) / (float)32768));
Use static cast

2021-04-05 15:57 UTC, pent0 commented on vita3k/modules/SceAudio/SceAudio.cpp
> +    float volume = ((float)((left + right) / (float)32768));
You can import 32768 constant and the channel flags by including vitasdk header

2021-04-05 15:57 UTC, pent0 commented on vita3k/audio/include/audio/state.h
> +    float volume = 100.0;
Make note also of its range

2021-04-05 22:22 UTC, tictakk commented
@pent0  added the notes and checks for flags. I also decided to keep the state of each channel so if the program only adjusts one channel, we still have data on what the other channel is (since they will be combined and used). I also made it do all the calculations in the **sceAudioOutSetVolume** function so the volume calculation isn't done each time mix_audio is called.

2021-04-05 22:29 UTC, Zangetsu38 requested changes
For push change just édit last commit and force push you can also squash your commit here

2021-04-05 22:29 UTC, Zangetsu38 commented on vita3k/modules/SceAudio/SceAudio.cpp
> +typedef enum SceAudioOutChannelFlag {
Remove typedef

2021-04-05 22:29 UTC, Zangetsu38 commented on vita3k/modules/SceAudio/SceAudio.cpp
> +} SceAudioOutChannelFlag;
Remove this just keep };

2021-04-06 06:11 UTC, pent0 commented on vita3k/modules/SceAudio/SceAudio.cpp
> +    const int right = (ch & SCE_AUDIO_VOLUME_FLAG_R_CH) ? vol[1] : prt->right_channel_volume;
I'm not sure about this line, maybe make a note in case we encounter regression

2021-04-06 06:12 UTC, pent0 commented on vita3k/modules/SceAudio/SceAudio.cpp
> +    const int right = (ch & SCE_AUDIO_VOLUME_FLAG_R_CH) ? vol[1] : prt->right_channel_volume;
Reason is maybe if only R_CH is available, volumes array size is only 1? Im not sure, but we have not seen this yet

2021-04-06 16:36 UTC, pent0 approved these changes

2021-04-06 16:37 UTC, Zangetsu38 approved these changes

2021-04-06 16:37 UTC, pent0 commented
Zang's requests are complimented

2021-04-06 16:37 UTC, merged