Implement and fix some modules functions
Vita3K/Vita3K pull request #1560
Opened 2021-12-22 13:13 UTC by bookmist

2021-12-22 13:21 UTC, Zangetsu38 commented on vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
> +    //SceKernelCallbackInfo *info = pInfo.get(host.mem);
you can delete this line if is not used anymore

2021-12-22 13:22 UTC, Zangetsu38 commented on vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
> +    pInfo->pCommon = cb->get_user_common_ptr(); //reinterpret_cast<void *>(cb->get_user_common_ptr().address());
same for here, no request keep // if using other things 🤔

2021-12-22 13:32 UTC, Zangetsu38 commented on vita3k/modules/SceNgsUser/SceNgs.cpp
> +    ngs::Voice *voice = voice_handle.get(host.mem);
```suggestion
    ngs::Voice *voice = voice_handle.get(host.mem);
    if (!voice) {
        return RET_ERROR(SCE_NGS_ERROR_INVALID_ARG);
    }
```

2021-12-22 13:32 UTC, Zangetsu38 commented on vita3k/modules/SceNgsUser/SceNgs.cpp
> +
```suggestion
    if (!voice) {
        return RET_ERROR(SCE_NGS_ERROR_INVALID_ARG);
    }
```

2021-12-22 13:42 UTC, Zangetsu38 commented on vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
> +            return RET_ERROR(-1);
ret_error here no have sense, RET_ERROR is just for priint enum error in log, but here log is already writed

2021-12-22 17:47 UTC, Zangetsu38 requested changes
No exactly what commit exactly, but your pr kill Catherine and other persona dancing, crash in boot
look for fix it before

2021-12-23 12:24 UTC, bookmist commented
> No exactly what commit exactly, but your pr kill Catherine crash in boot look for fix it before

I excluded commit causing this crash.

2021-12-23 12:25 UTC, Zangetsu38 approved these changes

2021-12-23 12:25 UTC, merged