Grammar corrections and build path fix.
Vita3K/Vita3K pull request #2001
Opened 2022-08-03 00:21 UTC by xero-lib

2022-08-03 04:15 UTC, Zangetsu38 requested changes
done all like i said, same for en-gb and no forget, if you touch on english lang, you need also change st'ring corresponding inside lang/state.h

2022-08-03 04:15 UTC, Zangetsu38 commented on lang/en-gb.xml
> +				<not_free_space>There is not enough free space on the disk.</not_free_space>
revert

2022-08-03 04:15 UTC, Zangetsu38 commented on lang/en-gb.xml
> +		<trophy_deleted>Trophy information saved for this user will be deleted.</trophy_deleted>
revert, official string is
"This trophy information saved on this system will be deleted."

2022-08-03 04:15 UTC, Zangetsu38 commented on lang/en-gb.xml
> -		<no_trophies>There are no trophies.
add user if you want, but no touch string, is official

2022-08-03 04:15 UTC, Zangetsu38 commented on lang/en-gb.xml
> +		<user_delete_msg>The following user will be deleted:</user_delete_msg>
revert

2022-08-03 04:15 UTC, Zangetsu38 commented on lang/en-gb.xml
> +		<user_delete_message>If you delete the user, that user's saved data (trophies, etc) will be deleted.</user_delete_message>
same

2022-08-03 04:15 UTC, Zangetsu38 commented on lang/en-gb.xml
> +		<later_version_already_installed>This version of the Vita3K software is already installed.</later_version_already_installed>
revert is official string

2022-08-03 11:08 UTC, Croden1999 commented
u can changed install dialog, not changed other strings, there are based on PSVita/PS4 language.

2022-08-04 00:06 UTC, Zangetsu38 commented on lang/en-gb.xml
> +		<app_close>The following application will close:</app_close>
Revert this i have said

2022-08-04 00:07 UTC, Zangetsu38 commented on vita3k/lang/include/lang/state.h
> +        { "save_delete", "Do you want to delete this saved data?" },
Good catch, copy past have added space

2022-08-04 00:22 UTC, xero-lib commented
Missed that revert, fixed now.

2022-08-04 02:53 UTC, Zangetsu38 commented on lang/en.xml
> +		<app_close>The following application will close:</app_close>
forget revert it

2022-08-04 03:15 UTC, Zangetsu38 approved these changes

2022-08-04 03:47 UTC, merged