[WIP] modules: Universal tracy macros (SceAudiodecUser as example)
Vita3K/Vita3K pull request #2007
Opened 2022-08-04 13:10 UTC by bookmist

I try to make universal macro, which can be used to log function parameters with tracy. Now this PR is only a demo, with one module as example.

2022-08-04 14:02 UTC, EXtremeExploit commented
hmm having the tracy macros defined in the module is not that great, you would have to copy pase them anywhere, maybe it would he nice to have them in utils or something like that, they will be used around the project

2022-08-04 14:39 UTC, bookmist commented
I was going to do so, but had no idea where to put this universal macro. So if utils is a good place - it's great.

2022-10-03 22:11 UTC, EXtremeExploit requested changes

2022-10-03 22:11 UTC, EXtremeExploit commented on vita3k/modules/include/modules/tracy.h
> +#include <mem/state.h>
also `#include <sstream>` for stringstream on linux end so compiler doesn't give an error on some systemd

2022-10-03 22:11 UTC, EXtremeExploit commented on vita3k/modules/include/modules/tracy.h
> +std::string to_debug_str<std::string>(const MemState &mem, std::string data) {
make this inline

2022-10-03 22:11 UTC, EXtremeExploit commented on vita3k/modules/include/modules/tracy.h
> +std::string to_debug_str(const MemState &mem) {
this inline too

2022-10-04 09:11 UTC, bookmist commented on vita3k/modules/include/modules/tracy.h
> +std::string to_debug_str(const MemState &mem) {
done. Thanks for help

2022-10-04 09:16 UTC, EXtremeExploit approved these changes

2022-10-04 13:00 UTC, merged