Russian Update
Vita3K/Vita3K pull request #2019
Opened 2022-08-14 16:48 UTC by Danik2343

Russian Update

2022-08-14 18:13 UTC, Croden1999 commented
oh my gosh it is.

2022-08-14 20:11 UTC, Zangetsu38 commented
Changé format kill comparaison

2022-08-16 10:49 UTC, Zangetsu38 commented on lang/ru.xml
> +</lang>
neede new line here

2022-08-27 04:48 UTC, Zangetsu38 commented
@Danik2343 you can fix formating and force push ?

2022-08-27 05:26 UTC, Croden1999 requested changes
there is wrong format.

2022-10-14 14:00 UTC, Croden1999 commented
plz push again, sir.

2023-05-05 17:44 UTC, Croden1999 commented
should close this pr, is outdated

2023-05-05 18:59 UTC, closed without merging