NID: Add __stack_chk_guard
Vita3K/Vita3K pull request #2028
Opened 2022-08-22 19:49 UTC by EXtremeExploit

2022-08-22 19:51 UTC, Zangetsu38 commented
missing function register

2022-08-22 19:52 UTC, EXtremeExploit commented
register?

2022-08-22 19:54 UTC, Zangetsu38 commented
yes register function stub

2022-08-22 20:44 UTC, EXtremeExploit commented
what?

2022-08-22 20:48 UTC, Macdu commented
@Zangetsu38 The stub implementation is already in the code (even before this PR), it's only the NID and bridge part that was missing.

2022-08-23 10:21 UTC, bookmist approved these changes

2022-08-23 11:11 UTC, Zangetsu38 requested changes

2022-08-23 11:11 UTC, Zangetsu38 commented on vita3k/modules/SceLibKernel/SceLibKernel.cpp
> +BRIDGE_IMPL(__stack_chk_guard)
register function inside this file, for now only set nid no have sense

2022-08-23 11:12 UTC, Zangetsu38 commented
> @Zangetsu38 The stub implementation is already in the code (even before this PR), it's only the NID and bridge part that was missing.

ah i see yes, very strange that

2022-08-23 12:40 UTC, merged