README: update
Vita3K/Vita3K pull request #2203
Opened 2022-11-23 18:19 UTC by nishinji

- ~~Remove showcase (located on website,there are a lot of games that currently work)~~

2023-02-14 06:51 UTC, CoffeeBrewer64 reviewed
Why would you want to remove the showcase? Maybe cut it down by a few but it serves as a way to show off what the emulator can do.

Also, line 48, is that the correct one? I've been told before that it's now 2020/2021/2022 by Zangetsu.

2023-03-31 19:54 UTC, CoffeeBrewer64 requested changes
I think a link to the showcase which is on the website would be better so that the person can still see it if they want to.

2023-03-31 19:57 UTC, CoffeeBrewer64 commented on README.md
> +Check our [quickstart](https://vita3k.org/quickstart) guide to make sure your computer meets the minimum requirements to run Vita3K.
This is **really** petty but the link should cover the full "quickstart guide" instead of just "quickstart".

2024-05-21 09:50 UTC, Macdu commented
I'm not entirely sure about the download counter badge given that it's reset after every update I believe.

2024-05-21 11:55 UTC, nishinji commented
> I'm not entirely sure about the download counter badge given that it's reset after every update I believe.

What you are saying is correct and I recognize it, but I didn't pay much attention to it.
Deleted.

2024-06-28 11:46 UTC, Macdu submitted a review, later dismissed

2024-08-07 17:14 UTC, scribam commented
@Macdu can this be merged since it has been approved?

2024-08-25 07:32 UTC, nishinji commented
VitaDB link is updated.
@scribam No one is objecting, so please merge :sob:.

2024-08-25 07:51 UTC, scribam approved these changes

2024-08-25 07:51 UTC, merged