gui: small fix and update
Vita3K/Vita3K pull request #2213
Opened 2022-12-03 16:38 UTC by nishinji

I don't know what the deleted lines were intended to exist, but I was able to correct them and will pr
- fix separater position
![スクリーンショット (532)](https://user-images.githubusercontent.com/107111782/205451243-ca685cec-5f36-48a6-a8cb-538c86115cbe.png)
- the number of pages should be in the middle.
![スクリーンショット (533)](https://user-images.githubusercontent.com/107111782/205451247-f54c8797-4513-47ec-95da-4ca8a22c78f7.png)
- It is my personal desire to open the manual directly

2022-12-03 16:48 UTC, Zangetsu38 commented
Hmm 🧐🤔 no have sense lol

2022-12-03 17:46 UTC, Croden1999 requested changes

2022-12-03 17:46 UTC, Croden1999 commented on vita3k/gui/src/app_context_menu.cpp
> +            }
there are no sense, liveaera menu is repeated.

2022-12-04 05:14 UTC, Zangetsu38 commented on vita3k/gui/src/app_context_menu.cpp
> +                open_manual(gui, emuenv, app_path);
keep wrong, code reépeat lol

2022-12-04 05:25 UTC, nishinji commented on vita3k/gui/src/app_context_menu.cpp
> +                open_manual(gui, emuenv, app_path);
:sob:

2022-12-06 04:21 UTC, Zangetsu38 commented on vita3k/gui/src/settings.cpp
> -                ImGui::SetCursorPosY(ImGui::GetCursorPosY() - (CALC_POS_TITLE > 0 ? CALC_POS_TITLE : -CALC_POS_TITLE));
revert this, sortry, i need check it for fix it myself

2022-12-08 04:11 UTC, Zangetsu38 approved these changes

2022-12-08 04:12 UTC, merged