Update zh-t.xml
Vita3K/Vita3K pull request #2356
Opened 2023-02-18 17:30 UTC by Kaitul

Update and improve the translation

2023-02-19 02:16 UTC, Croden1999 requested changes

2023-02-19 02:16 UTC, Croden1999 commented on lang/zh-t.xml
> +				<loading>載入中…</loading>
do not change this, is based on psvita system lang.

2023-02-19 02:16 UTC, Croden1999 commented on lang/zh-t.xml
> +				<saving_complete>保存完成。</saving_complete>
here

2023-02-19 02:16 UTC, Croden1999 commented on lang/zh-t.xml
> +				<warning_saving>保存中…
and here.

2023-02-19 02:16 UTC, Croden1999 commented on lang/zh-t.xml
> +		<data_delete>將要刪除的資料：</data_delete>
also this.

2023-02-19 02:21 UTC, Croden1999 requested changes

2023-02-19 02:21 UTC, Croden1999 commented on lang/zh-t.xml
> +		<history_version>{}版本</history_version>
also is based psvita lang

2023-02-19 02:21 UTC, Croden1999 commented on lang/zh-t.xml
> +		<updated>更新日期</updated>
here

2023-02-19 02:21 UTC, Croden1999 commented on lang/zh-t.xml
> +		<save_delete>確定要刪除此保存資料嗎？</save_delete>
here

2023-02-19 02:21 UTC, Croden1999 commented on lang/zh-t.xml
> +		<app_delete>將會刪除此應用程式及所有相關資料（包括保存資料）。</app_delete>
here

2023-02-19 02:21 UTC, Croden1999 commented on lang/zh-t.xml
> +		<please_wait>請稍候…</please_wait>
here

2023-02-19 02:21 UTC, Croden1999 commented on lang/zh-t.xml
> +		<clear_all>全部清除</clear_all>
and here

2023-02-19 02:21 UTC, Croden1999 commented on lang/zh-t.xml
> +			<preparing_start_app>正在準備啟動應用程式…</preparing_start_app>
there is right, not need change, is based on psvita lang.

2023-02-19 02:33 UTC, Croden1999 requested changes

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +				<updated>更新日期</updated>
here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +				<delete_saved_data>確定要刪除此保存資料嗎？</delete_saved_data>
here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +		<app_added_home>應用程式已追加至主頁畫面。</app_added_home>
here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +		<installing>安裝中…</installing>
here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +		<select_language>選擇語言。</select_language>
no need add translate, if no install firmware, there are no display normal text.

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +		<install_highly_recommended>強烈建議您安裝這兩個韌體檔案。</install_highly_recommended>
also here no need add translate, if no install firmware, there are no display normal text.

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +		<next>下一步</next>
no need translate

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +			<default>預設</default>
do not change this, is based on psvita

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +					<updated>更新日期</updated>
also this

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +				<delete>這個主題將被刪除。</delete>
here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +				<add_image>追加圖像</add_image>
here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +			<home_screen_backgrounds name="主頁畫面背景">
here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +				<add_background>追加背景</add_background>
here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +						<lang id="4">英文（美國）</lang>
also here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +						<lang id="512">葡萄牙文（葡萄牙）</lang>
here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +		<earned>獲得日期</earned>
is based on psvita lang, revert it.

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +		<grade>階級</grade>
also here

2023-02-19 02:33 UTC, Croden1999 commented on lang/zh-t.xml
> +		<updated>更新日期</updated>
here

2023-02-19 02:50 UTC, Croden1999 requested changes

2023-02-19 02:50 UTC, Croden1999 commented on lang/zh-t.xml
> +		<user_delete_message>若要刪除使用者，這位使用者的保存資料、獎盃也會一併被刪除。</user_delete_message>
no need change, is based on the ps4 user management lang

2023-02-19 02:50 UTC, Croden1999 commented on lang/zh-t.xml
> +		<user_deleted>使用者已刪除。</user_deleted>
also here

2023-02-19 02:50 UTC, Croden1999 commented on lang/zh-t.xml
> +		<version>{}版本</version>
revert it

2023-02-19 02:50 UTC, Croden1999 commented on lang/zh-t.xml
> +		<new_features>{}版本的追加機能</new_features>
also

2023-02-19 02:50 UTC, Croden1999 commented on lang/zh-t.xml
> + 		<new_version_available>Vita3K有可用的新版本。</new_version_available>
is based on psvita lang

2023-02-19 02:50 UTC, Croden1999 commented on lang/zh-t.xml
> +		<update_vita3k>要更新Vita3K嗎？</update_vita3k>
also here

2023-02-19 02:56 UTC, Croden1999 requested changes

2023-02-19 02:56 UTC, Croden1999 commented on lang/zh-t.xml
> +			<firmware_font_package_note>某些應用程式和亞洲區域字型支援需要韌體字型套件（一般建議安裝）。</firmware_font_package_note>
no need change, use english, if no install firmware, here not display the normal text.

2023-02-19 02:56 UTC, Croden1999 commented on lang/zh-t.xml
> +			<firmware_installing>安裝進行中，請稍候…</firmware_installing>
also

2023-02-19 02:56 UTC, Croden1999 commented on lang/zh-t.xml
> +			<delete_firmware>刪除韌體安裝檔案？</delete_firmware>
here

2023-02-19 03:00 UTC, Croden1999 requested changes

2023-02-19 03:00 UTC, Croden1999 commented on lang/zh-t.xml
> +		<details>詳細資料</details>
revert it.

2023-02-19 03:04 UTC, Croden1999 requested changes

2023-02-19 03:04 UTC, Croden1999 commented on lang/zh-t.xml
> +			<firmware_font_package_noteFirmware font package is needed for some applications and also for Asian regional font support. (Generally Recommended)</firmware_font_package_note>
wrong format

2023-02-19 03:04 UTC, Kaitul commented on lang/zh-t.xml
> +			<firmware_font_package_noteFirmware font package is needed for some applications and also for Asian regional font support. (Generally Recommended)</firmware_font_package_note>
fixed

2023-02-19 03:08 UTC, Croden1999 requested changes

2023-02-19 03:08 UTC, Croden1999 commented on lang/zh-t.xml
> +			<firmware_not_detected>未偵測到韌體，強烈建議安裝</firmware_not_detected>
revert it, here use english

2023-02-19 03:08 UTC, Croden1999 commented on lang/zh-t.xml
> +			<firmware_font_not_detected>未偵測到韌體字型，強烈建議為Live Area字型文字安裝</firmware_font_not_detected>
also

2023-02-19 03:12 UTC, Croden1999 submitted a review, later dismissed

2023-02-19 03:23 UTC, Croden1999 commented
i need check it again

2023-02-20 06:24 UTC, Croden1999 commented
not good
![image](https://user-images.githubusercontent.com/61804715/220027606-73d49e87-0c61-4b93-a2c3-00fc3938b832.png)
![image](https://user-images.githubusercontent.com/61804715/220027960-2df5cd97-d54c-4e40-b481-6abdd69da9f1.png)

2023-02-20 06:37 UTC, Croden1999 requested changes

2023-02-20 06:37 UTC, Croden1999 commented on lang/zh-t.xml
> +		<completed>Completed.</completed>
the "completed" is normal, revert it.

2023-02-20 06:37 UTC, Croden1999 commented on lang/zh-t.xml
> +		<installed>Installed:</installed>
also the "installed" is normal, revert it.

2023-02-20 06:40 UTC, Croden1999 commented
ur pr has conflicts that must be resolved, look this pr https://github.com/Vita3K/Vita3K/pull/2357

2023-02-20 13:36 UTC, Croden1999 commented
please Mr.@Zangetsu38 review this pr.

2023-02-20 17:40 UTC, Zangetsu38 commented
conflict, need rebase

2023-02-22 22:50 UTC, Croden1999 requested changes

2023-02-22 22:50 UTC, Croden1999 commented on lang/zh-t.xml
> +		<back>Back</back>
here is normal, revert it.

2023-02-22 23:00 UTC, Croden1999 requested changes

2023-02-22 23:00 UTC, Croden1999 commented on lang/zh-t.xml
> +		<download_firmware>下載韌體</download_firmware>
the "download_firmware" use english

2023-02-22 23:28 UTC, Croden1999 requested changes

2023-02-22 23:28 UTC, Croden1999 commented on lang/zh-t.xml
> +		<addcont>追加內容</addcont>
is based on psvita devkit/testkit lang

2023-03-01 19:25 UTC, Croden1999 commented
ur pr has conflicts that must be resolved

2023-03-03 02:05 UTC, Croden1999 approved these changes

2023-03-03 02:06 UTC, Croden1999 commented
please Mr.@Zangetsu38 review it

2023-03-03 04:48 UTC, Zangetsu38 approved these changes

2023-03-03 04:55 UTC, merged