gui/live area: Silence waring on info no found of frame.
Vita3K/Vita3K pull request #2679
Opened 2023-06-24 04:13 UTC by Zangetsu38

# About
- gui/live area: Silence waring on info no found of frame.
Some game register some strange info inside frame no exist on this style.

2023-06-27 13:39 UTC, Macdu requested changes
Please add an option to keep the old behavior.

2023-06-27 14:00 UTC, Zangetsu38 commented
> Please add an option to keep the old behavior.

i have already explain, you no ask option for keep old behavior
here you want option for disable my fix, have no sense, i FIX one probleme in gui.
i have already apply save fix in home and in user and more, no have sense want this option here.

i repeat again i fix proportion for no get deformed and keep good size/place

but if you no want black font when is outside viewport and only get blue in full screen is possible

2023-08-08 18:56 UTC, Zangetsu38 commented
> Please add an option to keep the old behavior.

is done by @nishinji

2023-08-08 22:11 UTC, Macdu approved these changes

2023-08-08 22:12 UTC, merged