welcome message translated to spanish
Vita3K/Vita3K pull request #3025
Opened 2023-10-27 06:54 UTC by elsamueldev

I will probably translate more things, but I wanted to open the PR already. You can accept it now if you want, and later I will open another one with more translations, no problem.

Please leave me comments correcting everything, it's my first time doing a PR for a serious repo.

2023-10-27 23:40 UTC, EXtremeExploit requested changes

2023-10-27 23:40 UTC, EXtremeExploit commented on lang/es.xml
> +		<line_seventh>Consulta la página de juegos comerciales y la lista de compatibilidad de Homebrew para ver qué juegos funcionan actualmente.</line_seventh>
```suggestion
		<line_seventh>Consulta la página de compatibilidad de juegos comerciales y Homebrew para ver qué juegos funcionan actualmente.</line_seventh>
```

2023-10-27 23:40 UTC, EXtremeExploit commented on lang/es.xml
> +		<line_tenth>Más ayuda disponible en el canal #help</line_tenth>
```suggestion
		<line_tenth>Más ayuda disponible en el canal #help del server de</line_tenth>
```
El boton de la invitación del server se agrega justo despues de esta línea, queda raro sino

2023-10-28 11:15 UTC, elsamueldev commented on lang/es.xml
> +		<line_tenth>Más ayuda disponible en el canal #help</line_tenth>
Entiendo, la verdad es que no hacía mucho sentido sin ver nada de Discord en el archivo. Pero, ¿no sería mejor poner "servidor"? Muchos hispanohablantes usan "server" indistintamente, lo sé, pero creo que quedaría mejor una traducción a español puro. Por eso he puesto "retroalimentación y pruebas" en vez de "feedback y testeo", por ponerte un ejemplo

2023-10-28 15:09 UTC, EXtremeExploit commented on lang/es.xml
> +		<line_tenth>Más ayuda disponible en el canal #help</line_tenth>
sisi, ningun problema en cambiar server por servidor, es costumbre

2023-10-28 15:23 UTC, EXtremeExploit approved these changes
gracias :D

2023-10-28 15:23 UTC, merged