UA (Ukraine language) translate
Vita3K/Vita3K pull request #3220
Opened 2024-02-17 10:41 UTC by Valeriy-Lednikov

I don't know the structure of the project, but I would like to add the Ukrainian language. Made a translation.

2024-02-17 11:11 UTC, bookmist commented
Move file to the "user" folder. The "system" folder contains only languages, presented in real PS Vita

2024-02-17 11:15 UTC, Croden1999 requested changes

2024-02-17 11:15 UTC, Croden1999 commented on lang/system/ua.xml
> +		<max>Максимум</max>
the text is overrun

2024-02-17 11:15 UTC, Croden1999 commented on lang/system/ua.xml
> +	</sys_apps_title>
remove `sys_apps_title`, this language isn't exist in param.sfo

2024-03-12 19:02 UTC, GameRuleUA commented
Valeriy-Lednikov, hello, can you give me link to download this file? I just want to add Ukrainian language into Vita3K

2024-03-30 21:33 UTC, Macdu commented
Superseded by #3251, thank you for your contribution!

2024-03-30 21:33 UTC, closed without merging