gui/lang: Update lang strings for Android version.
Vita3K/Vita3K pull request #3342
Opened 2024-08-04 13:18 UTC by Croden1999

- gui/lang: Update lang strings for Android version. 
   (https://github.com/Vita3K/Vita3K-Android/pull/606)

2024-08-04 21:21 UTC, Kitakatarashima commented
So can Indonesian and Malaysian be updated?

2024-08-04 21:39 UTC, Croden1999 commented
> So can Indonesian and Malaysian be updated?

Of course, if you wanted

2024-08-04 22:52 UTC, Kitakatarashima commented
L

> > So can Indonesian and Malaysian be updated?
> 
> Of course, if you want.

yeah, of course I want to, right? I don't want to do it in Indonesian and Malaysian languages. but yesterday the update file that I sent with my old Discord account wasn't received??

2024-08-05 03:20 UTC, Croden1999 commented
> yeah, of course I want to, right? I don't want to do it in Indonesian and Malaysian languages. but yesterday the update file that I sent with my old Discord account wasn't received??

I didn't see your message. You can sent your lang files on here or push my e-mail

2024-08-05 16:51 UTC, Kitakatarashima commented
> > yeah, of course I want to, right? I don't want to do it in Indonesian and Malaysian languages. but yesterday the update file that I sent with my old Discord account wasn't received??
> 
> I didn't see your message. You can sent your lang files on here or push to my e-mail

the file is no longer there, now it's stuck on my smartphone. Previously I had to create the Lang file again and update it again.

2024-08-06 01:57 UTC, Kitakatarashima commented
> > yeah, of course I want to, right? I don't want to do it in Indonesian and Malaysian languages. but yesterday the update file that I sent with my old Discord account wasn't received??
> 
> I didn't see your message. You can sent your lang files on here or push to my e-mail
here is the file but in Indonesian for now, if only in Malaysian then maybe next week at the latest because I don't have much time because I have a lot of things to do in the real world and I have to take care of my YouTube channel. Sorry
[id.zip](https://github.com/user-attachments/files/16504282/id.zip)

2024-08-06 11:43 UTC, Kitakatarashima commented
bro, here are the files for both languages, Malaysian and correct Indonesian because there was something wrong hehehe 😅 sorry, I'll do it quickly because I can't calm down if there's a task I haven't finished yet
[id.zip](https://github.com/user-attachments/files/16509717/id.zip)

2024-08-07 12:26 UTC, Kitakatarashima commented
Bro, send the Lang strings file that Bro Croden wants to add to the Lang file so I can immediately translate it into Indonesian and Malaysian

2024-08-07 17:26 UTC, Kitakatarashima commented
> @Kitakatarashima You can see changes to this file and update your language files. (https://github.com/Vita3K/Vita3K/pull/3342/files#diff-f9148b3c71a765e9ffff531470dc0aaf72ab1ba4379ff8657155925ac84eaded)

This is the latest update file for Indonesian and Malaysian languages, bro
[in and ms update.zip](https://github.com/user-attachments/files/16532109/in.and.ms.update.zip)

2024-08-09 07:53 UTC, Kitakatarashima commented
Finally I've finished the update, I've checked, there are no more translation errors, just waiting for Preview and Marge 😀

2024-08-09 13:34 UTC, Zangetsu38 commented
> Finally I've finished the update, I've checked, there are no more translation errors, just waiting for Preview and Marge 😀

Homer is not here 😎

2024-08-25 14:55 UTC, Kitakatarashima commented
I just wanted to ask, bro, @Croden1999 when will the preview and marge be??

2024-08-25 15:56 UTC, Croden1999 commented
> I just wanted to ask, bro, @Croden1999 when will the preview and marge be??

Waiting devs review this pr.

2024-08-26 00:31 UTC, Kitakatarashima commented
@Macdu Do the Indonesian and Malaysian languages have to be changed too?

2024-08-26 03:58 UTC, Croden1999 commented
> Really sorry for taking so much time. I have a few nitpicks. Except that, please do not merge android specific modifications while the android version itself it not yet merged to master.

I understand, I only add language xml&strings, Mr. Macdu.

2024-08-27 08:20 UTC, Croden1999 commented on lang/system/en-gb.xml
>  1. Do you have installed firmware?
Done, sir.

2024-08-28 06:59 UTC, Kitakatarashima commented
Bro @Croden1999 I want to ask whether the Indonesian and Malaysian languages should be changed too??

2024-08-29 19:56 UTC, Macdu commented
> > Really sorry for taking so much time. I have a few nitpicks. Except that, please do not merge android specific modifications while the android version itself it not yet merged to master.
> 
> I understand, I only add language xml&strings, Mr. Macdu.

Yes, but it's a bit weird to have only android strings in the main version. Also if I ever decide to change the overlay, we'll end up with strings on master that do not match anything

2024-08-30 03:31 UTC, Croden1999 commented
> > > Really sorry for taking so much time. I have a few nitpicks. Except that, please do not merge android specific modifications while the android version itself it not yet merged to master.
> > 
> > 
> > I understand, I only add language xml&strings, Mr. Macdu.
> 
> Yes, but it's a bit weird to have only android strings in the main version. Also if I ever decide to change the overlay, we'll end up with strings on master that do not match anything

Yes, I have also considered this issue, so I specially established corresponding PR associations in both repos, So, if that after the pr is merged, another pr can also be corresponding through rebase.
Or I move the Android strings to [Vita3K-Android#606](https://github.com/Vita3K/Vita3K-Android/pull/606)

2025-01-04 10:26 UTC, scribam requested changes
@Croden1999 I agree with Macdu, translations related to the android version should not be part of this repository. If you want your PR merged, can you please remove them? Also, there are conflicting files so you will have to rebase your changes

2025-01-04 15:42 UTC, Kitakatarashima commented
> @Croden1999 I agree with Macdu, translations related to the android version should not be part of this repository. If you want your PR merged, can you please remove them? Also, there are conflicting files so you will have to rebase your changes

which one is it and is there anything else I need to change or not??

2025-02-02 11:35 UTC, scribam commented
I will review this PR again when:
- The "for_android" translation strings will be removed
- The code will be up to date with `master` with all conflicts resolved

Thank you for all the changes you have made so far

2025-04-06 22:09 UTC, closed without merging