lang: Translate some strings into simplified Chinese.
Vita3K/Vita3K pull request #3440
Opened 2024-11-11 18:58 UTC by Dicot0721

2024-11-11 20:55 UTC, Zangetsu38 commented on lang/system/zh-s.xml
> +		<date_time name="日期&amp;时间">
Amp ?

2024-11-11 20:56 UTC, Zangetsu38 commented on lang/system/zh-s.xml
> +			<parental_controls>家长监控</parental_controls>
No need change, it used official string

2024-11-11 20:56 UTC, Zangetsu38 commented on lang/system/zh-s.xml
> +			<state id = "1">可以启动</state>
Same

2024-11-12 03:12 UTC, Croden1999 commented
有些翻译是基于PSVita的官方文本，无需改动。除此之外，还有一些字符串没有添加lang，你有一部分翻译文本是不起作用的

2024-11-12 03:12 UTC, Croden1999 commented
有些翻译是基于PSVita的官方文本，无需改动。除此之外，还有一些字符串没有添加lang，你有一部分翻译文本是不起作用的

2024-11-12 04:23 UTC, Croden1999 requested changes

2024-11-12 04:23 UTC, Croden1999 commented on lang/system/zh-s.xml
> +		<core name="内核">
内核对应应该是kernel，原来的翻译更好符合

2024-11-12 05:03 UTC, Zangetsu38 commented on lang/system/zh-s.xml
> +		<date_time name="日期&amp;时间">
revert it so, here is not code, is litteraly string in xml

2024-11-12 07:04 UTC, Croden1999 commented
> 一些添加的翻译字符串是在[f1df4b3](https://github.com/Vita3K/Vita3K/commit/f1df4b3b335bf4568642981715e2b6c1736fd6f1) 中新增的

哦，确实，我的错，有一段时间没有查看了

2024-12-03 22:55 UTC, Macdu commented
@Croden1999 Is the PR fine for you?

2024-12-20 12:42 UTC, Croden1999 commented
> @Croden1999 Is the PR fine for you?

Lgtm, sorry, sir. It's been too busy at work lately

2024-12-31 13:34 UTC, scribam approved these changes

2024-12-31 13:35 UTC, merged